@startuml
start
if(are there groups?) then (yes)
    :start with placing the groups first;
    repeat :iterate over all available chairs;
        
    repeat while (more available chairs)
else (no)
    :start with placing the individuals; 
@enduml